#               YAML parameter file
# H: python-list containing different H values for DEM's
# H: [H1, H2, H3, ...]
#
# H_wt: weight for corresponding H-value
# H_wt: [H1_wt, H2_wt, H3_wt, ...]
#
# seed: seed value for random no generator(choosing seed as prime no. gives best results)
# seed: [seed1, seed2, seed3, ...]
#
# elev_range: max and min bound on elevation values
# elev_range: [min_elev, max_elev]
# 
# DEMcreator_option: SS OR fm2D
# 
# Specify the gradient values 
# north_west         north            north_east
#                      |
#                      |
#                      |
# west  _____________center _____________  east
#                      |
#                      |
#                      |
# south_west         south            south_east 
#
# north: 60 (float)
# north_west: 20 (float)
# west: 5 (float)
# south_west: 25 (float)
# south: 45 (float)
# south_east: 55 (float)
# east: 25 (float)
# north_east: 60 (float)
# center: 52 (float)
#
# Three_DplotDEM: y/Y or n/N (depending on weather you want to plot eroded DEM as 3-D plot) 
# response : Depends on weather you to run Decision tree module(y for yes OR n/N for No)
#            You should specify n/N if decision_tree.pkl file is already present in Source Code directory  
#
# Features related to agricultural land
# min_area: minimum area of a filed(integer)
# max_area: maximum area of a filed(integer)
# aspect_ratio: ration of lenght to width (float)
# agri_area_limit: ratio of area of agriculture to entire grid (0 < float < 1)
# next_patch_orientation_probability: probability of next patch having
#                          the same orientation as previous patch (0 < float < 1)
#NAME OF FILES IN training_data directory
# training_data_elev: new_elev.asc
# training_data_elev: new_land.asc
# training_data_elev: new_rivers.asc
#
#
---
H: [0.85, 0.7, 0.6, 0.4]
H_wt: [0.6, 0.2, 0.1, 0.1]
seed: [19, 17, 11, 37]
elev_range: [0, 1300]
max_level: 9
river_drop: 10
counter: 1
DEMcreator_option: fm2D
north: 60
north_west: 20
west: 5
south_west: 25
south: 45
south_east: 55
east: 25
north_east: 60
center: 52
Three_DplotDEM: n
output_dir: Output
response: n
min_area: 100
max_area: 600
aspect_ratio: 2.1
next_patch_orientation_probability: 0.8
agri_area_limit: 0.25
training_data_elev: new_elev.asc
training_data_landcover: new_land.asc
training_data_river: new_rivers.asc
...
